baseURL = "https://www.h-dawg.de"
title = "Haukes Blog"
theme = "beautifulhugo"
locale = "de"
DefaultContentLanguage = "de"

[pagination]
  pagerSize = 5

[Params]
  subtitle = "...nur ein bisschen wirres zeug..."
  favicon = "favicon.svg"
  logo = "favicon.svg"
  dateFormat = "02.01.2006"
  since = 2005
  readingTime = true
  wordCount = true
  socialShare = false
  showRelatedPosts = true
  rss = true
  selfHosted = false

[Params.search]
  provider = "fuse"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  [permalinks.page]
    posts = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params.author]
  name = "Hauke"
  website = "/about"
  email = "hauke@h-dawg.de"
  twitter = "hwesselmann"
  github = "hwesselmann"
  instagram = "hwesselmann78"
  gitlab = "hwesselmann"
  mastodon = "https://vivaldi.social/@hwesselmann"
  linkedin = "haukewesselmann"

[[menu.main]]
    name = "über mich"
    url = "page/about/"
    weight = 1

[[menu.main]]
    identifier = "blog"
    name = "blog"
    weight = 2

[[menu.main]]
    parent = "blog"
    name = "posts"
    url = "posts/"
    weight = 1

[[menu.main]]
    parent = "blog"
    name = "tags"
    url = "tags/"
    weight = 2

[[menu.main]]
    parent = "blog"
    name = "kategorien"
    url = "categories/"
    weight = 3

[[menu.main]]
    identifier = "datenschutz"
    name = "datenschutz"
    url = "page/datenschutz/"
    weight = 3

[[menu.main]]
    name = "impressum"
    url = "page/impressum/"
    weight = 4